URL = "https://www.saucedemo.com/"
USERNAME = "standard_user"
PASSWORD = "secret_sauce"
ITEM_1 = "Sauce Labs Backpack"
ITEM_2 = "Sauce Labs Bike Light"
ITEM_3 = "Sauce Labs Bolt T-Shirt"
ITEM_4 = "Sauce Labs Fleece Jacket"
ITEM_5 = "Sauce Labs Onesie"
ITEM_6 = "Test.allTheThings() T-Shirt (Red)"

#XPATHS
BTN_ADDTOCARD = "xpath=/html/body/div/div/div/div[2]/div/div/div[2]/button"
BTN_BACKTOPRODUCTS = "xpath=/html/body/div/div/div/div[1]/div[2]/div/button"
BTN_BASKET = "xpath=/html/body/div/div/div/div[1]/div[1]/div[3]/a"
BTN_CHECKOUT = "xpath=/html/body/div/div/div/div[2]/div/div[2]/button[2]"
BTN_CONTINUE = "xpath=/html/body/div/div/div/div[2]/div/form/div[2]/input"
BTN_FINISH = "xpath=/html/body/div/div/div/div[2]/div/div[2]/div[9]/button[2]"
FIELD_FIRST_NAME = "xpath=/html/body/div/div/div/div[2]/div/form/div[1]/div[1]/input"
FIELD_LAST_NAME = "xpath=/html/body/div/div/div/div[2]/div/form/div[1]/div[2]/input"
FIELD_POSTAL_CODE = "xpath=/html/body/div/div/div/div[2]/div/form/div[1]/div[3]/input"

FIRST_NAME = "Kenn"
LAST_NAME = "Trinidad"
POSTAL_CODE = "12345"